create table if not exists public.inti_survey_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text,
  user_agent text,
  answers jsonb not null,
  client_token text,
  constraint answers_is_object check (jsonb_typeof(answers) = 'object')
);

alter table public.inti_survey_responses enable row level security;

revoke all on public.inti_survey_responses from anon, authenticated;
grant insert on public.inti_survey_responses to anon, authenticated;

create policy "anon can insert survey responses"
on public.inti_survey_responses
for insert
to anon, authenticated
with check (
  jsonb_typeof(answers) = 'object'
  and pg_column_size(answers) < 30000
);

create index if not exists inti_survey_responses_created_at_idx
on public.inti_survey_responses (created_at desc);

-- Public aggregate only: no raw answers exposed.
create or replace function public.inti_survey_summary()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'responses', count(*),
    'last_response_at', max(created_at)
  )
  from public.inti_survey_responses;
$$;

grant execute on function public.inti_survey_summary() to anon, authenticated;
